name: Code Quality

on: [push]

jobs:

  code_style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.2

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Check code formatting with black
        run: poetry run black  --check src tests

      - name: Run flake8
        run: poetry run flake8 src tests
