name: Tests

on: [push]

jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
      max-parallel: 4
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.3

      - name: Install Dependencies
        run: |
          poetry install

      - name: Test
        run: |
          make test
          poetry run coverage report -m
